/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.consulta;

import visao.consulta.ConsPadrao;
import controle.PecaFactory;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.bean.Peca;

/**
 *
 * @author Bruno Reinicke
 */
public class ConsPeca extends ConsPadrao {

    private JTextField jTFIdPeca;
    
    /**
     * Creates new form ConsPeca
     */
    public ConsPeca() {
        initComponents();
        super.setSize();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de peças");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsPeca().setVisible(true);
            }
        });
    }

    @Override
    public void listar(String info) {
        List<Peca> list;
        
        if (info.equals(""))
           list = (List<Peca>) new PecaFactory().consultar("");
        else
           list = (List<Peca>) new PecaFactory().consultar(" where nome like '"+info+"%'");      
        String colunas[]   = {"ID", "Ano", "Categoria", "Marca", "Nome", 
                            "Preço", "Quantidade", "Fornecedor"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        
        for (int i = 0; i < list.size(); i++) {
            modelo.addRow(new String[]{
                list.get(i).getId().toString(), 
                list.get(i).getAno() + "", 
                list.get(i).getCategoria(),
                list.get(i).getMarca(),
                list.get(i).getNome(),
                "R$ " + new DecimalFormat("#,##0.00").format(list.get(i).getPreco()),
                list.get(i).getQtde()+ "",
                list.get(i).getForn().getNome(),
            });
        }
        super.getTable().setModel(modelo);
    }    

    public void setJTFIdPeca(JTextField jTFIdPeca) {
        this.jTFIdPeca = jTFIdPeca;
    }
    
    @Override
    public void excluir() {
        super.excluirPadrao(new PecaFactory());           
    }

    @Override
    public void preencherCad(Vector vect) {
        if (super.ehNome) {
            super.jTFNome.setText(vect.get(4).toString());
            this.jTFIdPeca.setText(vect.get(0).toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}