/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.consulta;

import controle.CarroFactory;
import java.util.List;
import java.util.Vector;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.bean.Carro;

/**
 *
 * @author Bruno Reinicke
 */
public class ConsCarro extends ConsPadrao {

    private JTextField jTFAno;
    private JTextField jTFCidade;
    private JTextField jTFCliente;
    private JTextField jTFIdCliente;
    private JTextField jTFMarca;
    private JTextField jTFNomeCar;
    private JTextField jTFPais;
    private JTextField jTFPlaca;
    private JTextField jTFUF;
    private JTextField jTFIdCarro;
    private List<Carro> list;
    
    /**
     * Creates new form ConsCarro
     */    
    public ConsCarro() {
        initComponents();
        super.setSize();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de carros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsCarro().setVisible(true);
            }
        });
    }

    public void setJTFIdCarro(JTextField jTFIdCarro) {
        this.jTFIdCarro = jTFIdCarro;
    }
    
    @Override
    public void listar(String info) {
        if (info.equals(""))
           list = (List<Carro>) new CarroFactory().consultar("");
        else
           list = (List<Carro>) new CarroFactory().consultar(" where placa like '"+info+"%'");      
        String colunas[]   = {"ID", "Ano", "Cidade", "Marca", "Nome", "País", "Placa", "UF", "Cliente"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        
        for (int i = 0; i < list.size(); i++) {
            modelo.addRow(new String[]{
                list.get(i).getId().toString(), 
                String.valueOf(list.get(i).getAno()), 
                list.get(i).getCidade(),
                list.get(i).getMarca(),
                list.get(i).getNome(),
                list.get(i).getPais(),
                list.get(i).getPlaca(),
                list.get(i).getUf(),
                list.get(i).getDono().getNome()
            });
        }
        super.getTable().setModel(modelo);
    }

    @Override
    public void excluir() {
        super.excluirPadrao(new CarroFactory());
    }

    @Override
    public void preencherCad(Vector vect) {
        if (super.ehNome) {
            super.jTFNome.setText(vect.get(4).toString());
            this.jTFIdCarro.setText(vect.get(0).toString());
        }
        if (super.cadastro) {
            this.jTFIdCarro.setText(vect.get(0).toString());
            this.jTFAno.setText(vect.get(1).toString());
            this.jTFCidade.setText(vect.get(2).toString());
            this.jTFMarca.setText(vect.get(3).toString());
            this.jTFNomeCar.setText(vect.get(4).toString());
            this.jTFPais.setText(vect.get(5).toString());
            this.jTFPlaca.setText(vect.get(6).toString());
            this.jTFUF.setText(vect.get(7).toString());
            this.jTFCliente.setText(vect.get(8).toString());
            this.jTFIdCliente.setText(((Carro) list.get(super.row)).getDono().getId()+"");
        }
    }

    public void setjTFAno(JTextField jTFAno) {
        this.jTFAno = jTFAno;
    }

    public void setjTFCidade(JTextField jTFCidade) {
        this.jTFCidade = jTFCidade;
    }

    public void setjTFCliente(JTextField jTFCliente) {
        this.jTFCliente = jTFCliente;
    }

    public void setjTFIdCliente(JTextField jTFIdCliente) {
        this.jTFIdCliente = jTFIdCliente;
    }

    public void setjTFMarca(JTextField jTFMarca) {
        this.jTFMarca = jTFMarca;
    }

    public void setjTFNomeCar(JTextField jTFNomeCar) {
        this.jTFNomeCar = jTFNomeCar;
    }

    public void setjTFPais(JTextField jTFPais) {
        this.jTFPais = jTFPais;
    }

    public void setjTFPlaca(JTextField jTFPlaca) {
        this.jTFPlaca = jTFPlaca;
    }

    public void setjTFUF(JTextField jTFUF) {
        this.jTFUF = jTFUF;
    }

    public void setjTFIdCarro(JTextField jTFIdCarro) {
        this.jTFIdCarro = jTFIdCarro;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}