/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.cadastro;

import controle.AdminFactory;
import controle.UsuaFactory;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.bean.Administrador;
import modelo.bean.Usuario;
import visao.consulta.ConsAdministrador;
import visao.consulta.ConsUsuario;

/**
 *
 * @author Bruno Reinicke
 */
public class CadAdministrador extends CadPadrao {

    private String idade;
    
    /**
     * Creates new form CadAdministrador
     */
    public CadAdministrador() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.jTFIdUsuario.setVisible(false);
        this.jTFUsuario.setEnabled(false);
        this.idade = "";
        this.jTFIdade.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFIdUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFCidade = new javax.swing.JTextField();
        jTFIdade = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jTFPais = new javax.swing.JTextField();
        jTFSexo = new javax.swing.JTextField();
        jTFUF = new javax.swing.JTextField();
        jBtnPesqUsuar = new javax.swing.JButton();
        jTFUsuario = new javax.swing.JTextField();
        jFTFCpf = new javax.swing.JFormattedTextField(super.getMascCPF());
        jFTFDtNasc = new javax.swing.JFormattedTextField(super.getMascData());
        jfFTFRg = new javax.swing.JFormattedTextField(super.getMascRG());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de administradores");
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Cidade:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Data de nascimento:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Idade:");

        jLabel5.setText("Nome:");

        jLabel6.setText("País:");

        jLabel7.setText("RG:");

        jLabel8.setText("Sexo:");

        jLabel9.setText("UF:");

        jLabel10.setText("Usuário:");

        jTFIdade.setEditable(false);
        jTFIdade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFIdadeFocusLost(evt);
            }
        });
        jTFIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdadeActionPerformed(evt);
            }
        });
        jTFIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFIdadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFIdadeKeyReleased(evt);
            }
        });

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jTFUF.setToolTipText("");

        jBtnPesqUsuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPesqUsuar.setText("...");
        jBtnPesqUsuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnPesqUsuarMouseClicked(evt);
            }
        });

        jTFUsuario.setEditable(false);
        jTFUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTFUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTFUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFUsuario.setMinimumSize(new java.awt.Dimension(64, 25));
        jTFUsuario.setPreferredSize(new java.awt.Dimension(64, 25));
        jTFUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });

        jFTFDtNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDtNascFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTFIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFCidade)
                            .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNome)
                            .addComponent(jTFUF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTFSexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                            .addComponent(jTFPais, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jfFTFRg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPesqUsuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jFTFDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFTFDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jfFTFRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesqUsuar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdadeActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jBtnPesqUsuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPesqUsuarMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            ConsUsuario conUsua = new ConsUsuario();
            conUsua.setVisible(true);
            conUsua.setEhNome(true);
            conUsua.setAdmin(true);
            conUsua.listar("");
            conUsua.setJTFNome(this.jTFUsuario);
            conUsua.setJtfIdfUsuario(this.jTFIdUsuario);
            addLstCons(conUsua);
        });
    }//GEN-LAST:event_jBtnPesqUsuarMouseClicked

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jTFIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFIdadeFocusLost
  
    }//GEN-LAST:event_jTFIdadeFocusLost

    private void jTFIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdadeKeyPressed
        
    }//GEN-LAST:event_jTFIdadeKeyPressed

    private void jTFIdadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdadeKeyReleased
        this.idade = super.getApenasNros(this.idade, evt, jTFIdade);
        jTFIdade.setText(this.idade);
    }//GEN-LAST:event_jTFIdadeKeyReleased

    private void jFTFDtNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDtNascFocusLost
        int idade = super.getAnosEntDt(jFTFDtNasc.getText());
        this.jTFIdade.setText(String.valueOf(idade));
    }//GEN-LAST:event_jFTFDtNascFocusLost

    @Override
    public void salvar() {
        if (!this.jTFUsuario.getText().equals("")) {
            Object objAdm = new AdminFactory().consultar(" where idUsuario = " + Integer.valueOf(jTFIdUsuario.getText()));
        
            if (((List<Administrador>) objAdm).isEmpty() || (!getJtfID().getText().equals(""))) {
                Administrador adm = new Administrador();
                adm.setCidade(this.jTFCidade.getText());
                adm.setCpf(this.jFTFCpf.getText());
                adm.setDataNasc(this.validarData("nascimento", this.jFTFDtNasc.getText(), ""));
                if (!super.strTrim(this.jTFIdade.getText()).equals(""))
                    adm.setIdade(Integer.valueOf(this.jTFIdade.getText()).intValue());
                else
                    adm.setIdade(0);
                adm.setNome(this.jTFNome.getText());
                adm.setPais(this.jTFPais.getText());
                adm.setRg(this.jfFTFRg.getText());
                adm.setSexo(this.jTFSexo.getText());
                adm.setUf(this.jTFUF.getText());

                Object objUsu = new UsuaFactory().consultar(Integer.valueOf(jTFIdUsuario.getText()));
                adm.setUsu((Usuario) ((List<Usuario>) objUsu).get(0));
                
                if (!getJtfID().getText().equals(""))
                    adm.setId(Integer.valueOf(getJtfID().getText()));
                if (!super.bErro)
                    super.confirmar(new AdminFactory(), adm, "AdministradorPU");
                super.bErro = false;
            } else
                JOptionPane.showMessageDialog(null, "Não é possível cadastrar: administrador já cadastrado para o usuário selecionado.");
        } else
            JOptionPane.showMessageDialog(null, "Não é possível cadastrar: campo usuário é obrigatório e não está preenchido.");
    }

    @Override
    public void excluir() {
        new AdminFactory().excluir(Integer.valueOf(getJtfID().getText()));
    }

    @Override
    public void selecionar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsAdministrador conAdm = new ConsAdministrador();
                conAdm.setVisible(true);
                conAdm.setCadastro(true);
                conAdm.setjTFIdAdmin(getJtfID());
                conAdm.setJTFNome(jTFNome);
                conAdm.setjTFCidade(jTFCidade);
                conAdm.setjFTFCpf(jFTFCpf);
                conAdm.setjFTFDtNascimento(jFTFDtNasc);
                conAdm.setjTFIdUsuario(jTFIdUsuario);
                conAdm.setjTFIdade(jTFIdade);
                conAdm.setjTFPais(jTFPais);
                conAdm.setjFTFRg(jfFTFRg);
                conAdm.setjTFUf(jTFUF);
                conAdm.setjTFUsuario(jTFUsuario);
                conAdm.setjTFNome(jTFNome);
                conAdm.setjTFSexo(jTFSexo);
                conAdm.listar("");
                addLstCons(conAdm);
            }
        });
    }

    @Override
    public void limpar() {
        getJtfID().setText("");
        this.jTFCidade.setText("");
        this.jFTFCpf.setValue(null);
        this.jFTFDtNasc.setValue(null);
        this.jTFIdUsuario.setText("");
        this.jTFIdade.setText("");
        this.jTFNome.setText("");
        this.jTFPais.setText("");
        this.jfFTFRg.setValue(null);
        this.jTFSexo.setText("");
        this.jTFUF.setText("");
        this.jTFUsuario.setText("");
        this.idade = "";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPesqUsuar;
    private javax.swing.JFormattedTextField jFTFCpf;
    private javax.swing.JFormattedTextField jFTFDtNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFCidade;
    private javax.swing.JTextField jTFIdUsuario;
    private javax.swing.JTextField jTFIdade;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFPais;
    private javax.swing.JTextField jTFSexo;
    private javax.swing.JTextField jTFUF;
    private javax.swing.JTextField jTFUsuario;
    private javax.swing.JFormattedTextField jfFTFRg;
    // End of variables declaration//GEN-END:variables
}