/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.cadastro;

import controle.CarroFactory;
import controle.ClienteFactory;
import controle.OrdemServFactory;
import controle.PecaFactory;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.bean.Carro;
import modelo.bean.Cliente;
import modelo.bean.OrdemServico;
import modelo.bean.Peca;
import visao.consulta.ConsCarro;
import visao.consulta.ConsCliente;
import visao.consulta.ConsOrdemServico;
import visao.consulta.ConsPeca;

/**
 *
 * @author bruno
 */
public class CadOrdemServico extends CadPadrao {

    private Carro car;
    private List<Cliente> cli;
    private Peca pec;
    
    /**
     * Creates new form CadOremServico
     */
    public CadOrdemServico() {
        initComponents();
        this.jFTFDtAbertura.setValue(super.formatarData(LocalDate.now().toString()));
        this.jFTFDtAbertura.setEnabled(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.jTFIdPeca.setVisible(false);
        this.jTFIdCliente.setVisible(false);
        this.jTFIdCarro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jFTFDtAbertura = new javax.swing.JFormattedTextField(super.getMascData());
        jFTFDtPrevisao = new javax.swing.JFormattedTextField(super.getMascData());
        jFTFDtEncerramento1 = new javax.swing.JFormattedTextField(super.getMascData());
        jCbTrPeca = new javax.swing.JComboBox<>();
        jCbStatus = new javax.swing.JComboBox<>();
        jBtnPesqCli1 = new javax.swing.JButton();
        jBtnPesqCar = new javax.swing.JButton();
        jBtnPesqPeca = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTFNumero = new javax.swing.JTextField();
        jTFIdPeca = new javax.swing.JTextField();
        jTFIdCliente = new javax.swing.JTextField();
        jTFIdCarro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de ordens de serviço");

        jLabel1.setText("Número:");

        jLabel2.setText("Carro:");

        jLabel3.setText("Peça:");

        jLabel4.setText("Data de abertura:");

        jLabel5.setText("Data de encerramento:");

        jLabel6.setText("Data de previsão:");

        jLabel7.setText("Troca peça:");

        jLabel8.setText("Status:");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));

        jFTFDtAbertura.setEditable(false);
        jFTFDtAbertura.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFTFDtAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFDtAberturaActionPerformed(evt);
            }
        });

        jFTFDtPrevisao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDtPrevisaoFocusLost(evt);
            }
        });

        jFTFDtEncerramento1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDtEncerramento1FocusLost(evt);
            }
        });
        jFTFDtEncerramento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFDtEncerramento1ActionPerformed(evt);
            }
        });

        jCbTrPeca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em aberto", "Em execução", "Encerrada" }));

        jBtnPesqCli1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPesqCli1.setText("...");
        jBtnPesqCli1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnPesqCli1MouseClicked(evt);
            }
        });

        jBtnPesqCar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPesqCar.setText("...");
        jBtnPesqCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnPesqCarMouseClicked(evt);
            }
        });
        jBtnPesqCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqCarActionPerformed(evt);
            }
        });

        jBtnPesqPeca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPesqPeca.setText("...");
        jBtnPesqPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnPesqPecaMouseClicked(evt);
            }
        });
        jBtnPesqPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqPecaActionPerformed(evt);
            }
        });

        jLabel9.setText("Cliente:");

        jTFNumero.setEditable(false);
        jTFNumero.setBackground(java.awt.SystemColor.controlHighlight);
        jTFNumero.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jTFIdPeca.setEditable(false);

        jTFIdCliente.setEditable(false);

        jTFIdCarro.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFIdPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDtAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDtPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbTrPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jTextField9)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnPesqPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPesqCli1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPesqCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jFTFDtEncerramento1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jTFIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPesqCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBtnPesqCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jBtnPesqPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFDtAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFDtEncerramento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFDtPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbTrPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jTFIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFTFDtEncerramento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFDtEncerramento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFDtEncerramento1ActionPerformed

    private void jFTFDtEncerramento1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDtEncerramento1FocusLost
        if (this.jFTFDtEncerramento1.getText().equals("  /  /    "))
            this.jFTFDtEncerramento1.setValue(null);
    }//GEN-LAST:event_jFTFDtEncerramento1FocusLost

    private void jFTFDtPrevisaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDtPrevisaoFocusLost
        if (this.jFTFDtPrevisao.getText().equals("  /  /    "))
            this.jFTFDtPrevisao.setValue(null);
    }//GEN-LAST:event_jFTFDtPrevisaoFocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jBtnPesqCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesqCarActionPerformed

    private void jBtnPesqPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesqPecaActionPerformed

    private void jBtnPesqCli1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPesqCli1MouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            ConsCliente conCli = new ConsCliente();
            conCli.setVisible(true);
            conCli.setEhNome(true);
            conCli.listar("");
            conCli.setJTFNome(this.jTextField1);
            conCli.setJTFIdCliente(this.jTFIdCliente);
            addLstCons(conCli);
        });
    }//GEN-LAST:event_jBtnPesqCli1MouseClicked

    private void jBtnPesqCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPesqCarMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            ConsCarro conCar = new ConsCarro();
            conCar.setVisible(true);
            conCar.setEhNome(true);
            conCar.listar("");
            conCar.setJTFNome(this.jTextField9);
            conCar.setJTFIdCarro(this.jTFIdCarro);
            addLstCons(conCar);
        });
    }//GEN-LAST:event_jBtnPesqCarMouseClicked

    private void jBtnPesqPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPesqPecaMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
            ConsPeca conPeca = new ConsPeca();
            conPeca.setVisible(true);
            conPeca.setEhNome(true);
            conPeca.listar("");
            conPeca.setjTFNomFornec(this.jTextField10);
            conPeca.setJTFIdPeca(this.jTFIdPeca);
            addLstCons(conPeca);
        });
    }//GEN-LAST:event_jBtnPesqPecaMouseClicked

    private void jFTFDtAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFDtAberturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFDtAberturaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPesqCar;
    private javax.swing.JButton jBtnPesqCli1;
    private javax.swing.JButton jBtnPesqPeca;
    private javax.swing.JComboBox<String> jCbStatus;
    private javax.swing.JComboBox<String> jCbTrPeca;
    private javax.swing.JFormattedTextField jFTFDtAbertura;
    private javax.swing.JFormattedTextField jFTFDtEncerramento1;
    private javax.swing.JFormattedTextField jFTFDtPrevisao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFIdCarro;
    private javax.swing.JTextField jTFIdCliente;
    private javax.swing.JTextField jTFIdPeca;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void salvar() {
        if (!this.jTextField1.getText().equals("") &&
            !this.jTextField9.getText().equals("") &&
            !this.jTextField10.getText().equals("")) {
            Object carro = new CarroFactory().consultar("where id="+jTFIdCarro.getText()+" and idCliente="+jTFIdCliente.getText());
            if (!((List<Carro>) carro).isEmpty()) {
                OrdemServico os = new OrdemServico(); 

                os.setCliente(((Cliente) ((List<Cliente>) 
                    new ClienteFactory().consultar(
                     Integer.valueOf(jTFIdCliente.getText()))).get(0)));
                os.setCarro(((Carro) ((List<Carro>) 
                    new CarroFactory().consultar(
                     Integer.valueOf(jTFIdCarro.getText()))).get(0)));
                os.setPeca(((Peca) ((List<Peca>) 
                    new PecaFactory().consultar(
                     Integer.valueOf(jTFIdPeca.getText()))).get(0)));

                List<OrdemServico> lstOs = (List<OrdemServico>) 
                                            new OrdemServFactory()
                                            .consultar("from OrdemServico "+
                                                       "where idCliente = "+this.jTFIdCliente.getText()+
                                                       " and idCarro = "+this.jTFIdCarro.getText()+
                                                       " and idPeca = "+this.jTFIdPeca.getText()+
                                                       " and status <> 'Encerrada'");

                if (!getJtfID().getText().equals("") && !lstOs.isEmpty())
                    lstOs.remove(0);
                if (lstOs.isEmpty()) {
                    os.setDtAbertura(super.validarData("abertura", jFTFDtAbertura.getText(), ""));
                    os.setDtEncerramento(super.validarData("encerramento", jFTFDtEncerramento1.getText(), "igual"));
                    os.setPrazoEntrega(super.validarData("previsão", jFTFDtPrevisao.getText(), "maior"));
                    os.setTrocPeca(this.jCbTrPeca.getSelectedItem().toString());
                    os.setStatus(this.jCbStatus.getSelectedItem().toString());

                    if (!getJtfID().getText().equals("")) {
                        os.setId(Integer.valueOf(getJtfID().getText()));
                        os.setNumero(Integer.valueOf(this.jTFNumero.getText()));
                    }

                    if (!bErro) {
                        boolean peDisp = true;

                        if (os.getTrocPeca().equalsIgnoreCase("Sim")) {
                            int idPeca = os.getPeca().getId();
                            List<Peca> lstPeca = (List<Peca>) (new PecaFactory().consultar(idPeca));
                            if (lstPeca.get(0).getQtde() > 0) {
                                Peca peca = ((List<Peca>) (new PecaFactory().consultar(idPeca))).get(0);
                                peca.setQtde(peca.getQtde() - 1);
                                new PecaFactory().alterar(peca);
                            } else {
                                peDisp = false;
                                JOptionPane.showMessageDialog(null, "Peça indisponível no estoque, para dar continuidade à OS realize a compra.");
                            }
                        }
                        if (peDisp) 
                            this.confirmar(
                                os, 
                                "OrdemServicoPU", 
                                "from OrdemServico "+
                                "where idCliente = "+this.jTFIdCliente.getText()+
                                " and status <> 'Encerrada' "+
                                " and idCarro = "+this.jTFIdCarro.getText());
                    }
                } else
                    JOptionPane.showMessageDialog(null, 
                        "A peça "+os.getPeca().getNome()+ " do carro placa "+os.getCarro().getPlaca()+
                        " já está sendo tratada na OS "+lstOs.get(0).getNumero()+".");
                this.bErro = false;
            } else
                JOptionPane.showMessageDialog(null, "Não é permitido cadastrar uma OS em que o carro não seja do cliente selecionado.");
        } else
            JOptionPane.showMessageDialog(null, "Campos cliente, carro e peça são obrigatórios.");
    }

    @Override
    public void excluir() {
        new OrdemServFactory().excluir(Integer.valueOf(getJtfID().getText()));
    }

    @Override
    public void selecionar() {
        java.awt.EventQueue.invokeLater(() -> {
            ConsOrdemServico conos = new ConsOrdemServico();
            conos.setVisible(true);
            conos.setCadastro(true);
            conos.setIdUsuario(getIdUsuario());
            conos.listar("");
            conos.setjCbStatus(this.jCbStatus);
            conos.setjCbTrPeca(this.jCbTrPeca);
            conos.setjFTFDtAbertura(this.jFTFDtAbertura);
            conos.setjFTFDtEncerramento1(this.jFTFDtEncerramento1);
            conos.setjFTFDtPrevisao(this.jFTFDtPrevisao);
            conos.setjTextField1(this.jTextField1);
            conos.setjTextField10(this.jTextField10);
            conos.setjTextField9(this.jTextField9);
            conos.setjTextFieldIdOS(super.getJtfID());
            conos.setjTFNumero(this.jTFNumero);
            conos.setjTFIdCarro(this.jTFIdCarro);
            conos.setjTFIdCliente(this.jTFIdCliente);
            conos.setjTFIdPeca(this.jTFIdPeca);
            addLstCons(conos);
        });
    }

    @Override
    public void limpar() {
        this.jTextField1.setText("");
        this.jTextField10.setText("");
        this.jFTFDtEncerramento1.setValue(null);
        this.jFTFDtPrevisao.setValue(null);
        this.jCbStatus.setSelectedIndex(0);
        this.jCbTrPeca.setSelectedIndex(0);
        this.jTextField9.setText("");
        getJtfID().setText("");
        this.jTFIdCliente.setText("");
        this.jTFIdCarro.setText("");
        this.jTFIdPeca.setText("");
        this.jTFNumero.setText("");
    }
    
    public void confirmar(Object obj, String pers, String sql) {  
        if (getJtfID().getText().equals("")) {
            if (JOptionPane.showConfirmDialog(null, "Deseja confirmar o cadastro?") == 0) {
                new OrdemServFactory().salvar(obj, pers, sql);
                this.dispose();
            }
        } else {
            if (JOptionPane.showConfirmDialog(null, "Deseja confirmar a alteração?") == 0) {   
                new OrdemServFactory().alterar(obj);
                this.dispose();
            }
        }
    }
}