/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CarroFactory;
import controle.ClienteFactory;
import controle.OrdemServFactory;
import controle.PecaFactory;
import controle.UsuaFactory;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelo.bean.Carro;
import modelo.bean.Cliente;
import modelo.bean.OrdemServico;
import modelo.bean.Peca;

/**
 *
 * @author bruno
 */
public class CadOrdemServico extends CadPadrao {

    /**
     * Creates new form CadOremServico
     */
    public CadOrdemServico() {
        initComponents();
        this.jFTFDtAbertura.setValue(super.formatarData(LocalDate.now().toString()));
        this.jFTFDtAbertura.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jFTFDtAbertura = new javax.swing.JFormattedTextField(super.getMascData());
        jFTFDtPrevisao = new javax.swing.JFormattedTextField(super.getMascData());
        jFTFDtEncerramento1 = new javax.swing.JFormattedTextField(super.getMascData());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de ordens de serviço");

        jLabel1.setText("Cliente:");

        jLabel2.setText("Carro:");

        jLabel3.setText("Peça:");

        jLabel4.setText("Data de abertura:");

        jLabel5.setText("Data de encerramento:");

        jLabel6.setText("Data de previsão:");

        jLabel7.setText("Peça trocada:");

        jLabel8.setText("Status:");

        jFTFDtAbertura.setEditable(false);

        jFTFDtPrevisao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDtPrevisaoFocusLost(evt);
            }
        });

        jFTFDtEncerramento1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFDtEncerramento1FocusLost(evt);
            }
        });
        jFTFDtEncerramento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFDtEncerramento1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                        .addComponent(jTextField1)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFTFDtAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDtEncerramento1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDtPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFTFDtAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFTFDtEncerramento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFTFDtPrevisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFTFDtEncerramento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFDtEncerramento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFDtEncerramento1ActionPerformed

    private void jFTFDtEncerramento1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDtEncerramento1FocusLost
        if (this.jFTFDtEncerramento1.getText().equals("  /  /    "))
            this.jFTFDtEncerramento1.setValue(null);
    }//GEN-LAST:event_jFTFDtEncerramento1FocusLost

    private void jFTFDtPrevisaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFDtPrevisaoFocusLost
        if (this.jFTFDtPrevisao.getText().equals("  /  /    "))
            this.jFTFDtPrevisao.setValue(null);
    }//GEN-LAST:event_jFTFDtPrevisaoFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadOrdemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFTFDtAbertura;
    private javax.swing.JFormattedTextField jFTFDtEncerramento1;
    private javax.swing.JFormattedTextField jFTFDtPrevisao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void salvar() {
        OrdemServico os = new OrdemServico();
       
        os.setCliente(
            ((Cliente) ((List<Cliente>) new ClienteFactory()
                .consultar("from Cliente where nome like '" + jTextField1.getText() + "'")).get(0)));
        os.setCarro(
            ((Carro) ((List<Carro>) new CarroFactory()
                .consultar("from Carro where nome like '" + jTextField9.getText() + "'")).get(0)));
        os.setPeca(
            ((Peca) ((List<Peca>) new PecaFactory()
                .consultar("from Peca where nome like '" + jTextField10.getText() + "'")).get(0)));
   
        List<OrdemServico> lstOs = 
            (List<OrdemServico>) new OrdemServFactory().consultar(
                                                        "from OrdemServico "+
                                                        "where idCliente = "+os.getCliente().getId()+
                                                        " and idCarro = "+os.getCarro().getId()+
                                                        " and idPeca = "+os.getPeca().getId()+
                                                        " and status = 0");
        if (lstOs.isEmpty()) {
            os.setDtAbertura(super.validarData("abertura", jFTFDtAbertura.getText()));
            os.setPrazoEntrega(super.validarData("previsão", jFTFDtPrevisao.getText()));
            os.setDtEncerramento(super.validarData("encerramento", jFTFDtEncerramento1.getText()));
            
        /*    if (jTextField14.getText().equals("Sim"))
                os.setPecaTrocada(true);
            else
                os.setPecaTrocada(false);

            if (jTextField15.getText().equals("Em execução"))
                os.setStatus(0);
            else
                os.setStatus(1);*/

            if (!getJtfID().getText().equals("")) 
                os.setId(Integer.valueOf(getJtfID().getText()));
            
            if (!bErro)
                super.confirmar(new OrdemServFactory(), os, "OrdemServicoPU");
        } else
            JOptionPane.showMessageDialog(null, 
                "A peça "+os.getPeca().getNome()+ " do carro placa "+os.getCarro().getPlaca()+
                " já está sendo tratada na OS "+lstOs.get(0).getNumero()+".");
        this.bErro = false;
    }

    @Override
    public void excluir() {
        new OrdemServFactory().excluir(Integer.valueOf(getJtfID().getText()));
    }

    @Override
    public void selecionar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsOrdemServico conos = new ConsOrdemServico();
                conos.setVisible(true);
                conos.setCadastro(true);
                conos.setIdUsuario(getIdUsuario());
                conos.listar("");
            }
        });
    }

    @Override
    public void limpar() {
        this.jTextField1.setText("");
        this.jTextField10.setText("");
        this.jFTFDtEncerramento1.setValue(null);
        this.jFTFDtPrevisao.setValue(null);
        this.jTextField14.setText("");
        this.jTextField15.setText("");
        this.jTextField9.setText("");
    }
}