/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ClienteFactory;
import controle.OrdemServFactory;
import controle.UsuaFactory;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.bean.Cliente;
import modelo.bean.OrdemServico;
import modelo.bean.Usuario;

/**
 *
 * @author bruno
 */
public class ConsOrdemServico extends javax.swing.JFrame {

    /**
     * Creates new form ConsOrdemServico
     */
    private int idUsuario;
    private List<Object> lstOS;
    
    public ConsOrdemServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de ordens de serviço");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Cliente", "Carro", "Peça", "Data abertura", "Data encerramento", "Prazo de entrega", "Peça trocada", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable2ComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Remover filtro");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Filtrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2ComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (((List<Usuario>) new UsuaFactory().consultar(this.idUsuario)).get(0).getTipo() == 'C') {
            int idCliente = 
                ((Cliente)
                    ((List<Object>) 
                        (new ClienteFactory().consultar("from Cliente where idUsuario = " + this.idUsuario))).get(0)).getId();          
            lstOS = (List<Object>) new OrdemServFactory().consultar("from OrdemServico where idCliente = "+idCliente+" and status = 0");
        } else {
            lstOS = (List<Object>) new OrdemServFactory().consultar("from OrdemServico");
        } 
        this.carregarTabela("");
    }//GEN-LAST:event_formWindowOpened

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.carregarTabela(jTextField1.getText());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.carregarTabela("");
    }//GEN-LAST:event_jButton1MouseClicked

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    private void listarOrdensServ(DefaultTableModel modelo, String numero) {
        for (int i = 0; i < lstOS.size(); i++) {
            String status;
            String dtEncerramento = "";
            String pecTrocada = "Não";
            String dtPrevisao = "";
            
            if (numero.equals("") || 
               (Integer.valueOf(numero) == ((OrdemServico) lstOS.get(i)).getNumero())) {
                if (((OrdemServico) lstOS.get(i)).getStatus() == 0) 
                   status = "Em execução";
                else
                   status = "Encerrada"; 

                if (((OrdemServico) lstOS.get(i)).getDtEncerramento() != null) 
                   dtEncerramento = ((OrdemServico) lstOS.get(i)).getDtEncerramento().toString();

                if (((OrdemServico) lstOS.get(i)).isPecaTrocada())
                   pecTrocada = "Sim";

                if (((OrdemServico) lstOS.get(i)).getPrazoEntrega() != null) 
                   dtPrevisao = ((OrdemServico) lstOS.get(i)).getPrazoEntrega().toString();
                
                modelo.addRow(new String[]{
                    ((OrdemServico) lstOS.get(i)).getNumero().toString(), 
                    ((OrdemServico) lstOS.get(i)).getCliente().getNome(), 
                    ((OrdemServico) lstOS.get(i)).getCarro().getNome(),
                    ((OrdemServico) lstOS.get(i)).getPeca().getNome(),
                    ((OrdemServico) lstOS.get(i)).getDtAbertura().toString(),
                    dtEncerramento,
                    dtPrevisao,
                    pecTrocada,
                    status});
            }
        }
        jTable2.setModel(modelo);
    }
    
    private void carregarTabela(String numero) {
        String colunas[] = {"Número", "Cliente", "Carro", "Peça", "Data abertura", 
            "Data encerramento", "Prazo de entrega", "Peça trocada", "Status"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        
        jTable2.setModel(modelo);
        this.listarOrdensServ(modelo, numero);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}