/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.UsuaFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.bean.Usuario;

/**
 *
 * @author bruno
 */
public class Login extends JFrame {

    private JButton btnCadUsu;
    private JButton btnConsUsu;
    private JButton btnConsOS;
    private JButton btnCadOS;
    private JButton btnLogin;
    private JButton btnConsAdm;
    private JButton btnConsCar;
    private JButton btnConsClie;
    private JButton btnConsForn;
    private JButton btnConsPeca;
    private JButton btnCadAdm;
    private JButton btnCadCarro;
    private JButton btnCadCli;
    private JButton btnCadForn;
    private JButton btnCadPeca;
    private int idUsuario;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Usuário:");
        jLabel1.setToolTipText("");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("Senha:");
        jLabel2.setToolTipText("");
        jLabel2.setName(""); // NOI18N

        jButton1.setText("Entrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Usuario u = new Usuario();
        u.setUsuario(jTextField1.getText());
        u.setSenha(new String(jPasswordField2.getPassword()));
    
        if (new UsuaFactory().isLogged(u) != null) {
            this.idUsuario = ((Usuario) new UsuaFactory().isLogged(u).get(0)).getId();   
            
            if (((Usuario) new UsuaFactory().isLogged(u).get(0)).getTipo().equalsIgnoreCase("Administrador")) {
                this.btnCadUsu.setVisible(true);
                this.btnConsUsu.setVisible(true);
                this.btnCadOS.setVisible(true);
                this.btnConsAdm.setVisible(true);
                this.btnConsCar.setVisible(true);
                this.btnConsClie.setVisible(true);
                this.btnConsForn.setVisible(true);
                this.btnConsPeca.setVisible(true);
                this.btnCadAdm.setVisible(true);
                this.btnCadCarro.setVisible(true);
                this.btnCadCli.setVisible(true);
                this.btnCadForn.setVisible(true);
                this.btnCadPeca.setVisible(true);
            }
            this.btnConsOS.setVisible(true);
            this.btnLogin.setEnabled(false);
        } else
            JOptionPane.showMessageDialog(this, "Dados incorretos, verifique e tente novamente por favor.");
    }//GEN-LAST:event_jButton1MouseClicked

    public void setBtnCadUsu(JButton btnCadUsu) {
        this.btnCadUsu = btnCadUsu;
    }

    public void setBtnConsUsu(JButton btnConsUsu) {
        this.btnConsUsu = btnConsUsu;
    }

    public void setBtnConsOS(JButton btnConsOS) {
        this.btnConsOS = btnConsOS;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public JButton getBtnCadOS() {
        return btnCadOS;
    }

    public void setBtnCadOS(JButton btnCadOS) {
        this.btnCadOS = btnCadOS;
    }
    
    public JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    public JButton getBtnConsAdm() {
        return btnConsAdm;
    }

    public void setBtnConsAdm(JButton btnConsAdm) {
        this.btnConsAdm = btnConsAdm;
    }
    
    public JButton getBtnConsCar() {
        return btnConsCar;
    }

    public void setBtnConsCar(JButton btnConsCar) {
        this.btnConsCar = btnConsCar;
    }
    
    public JButton getBtnConsClie() {
        return btnConsClie;
    }

    public void setBtnConsClie(JButton btnConsClie) {
        this.btnConsClie = btnConsClie;
    }

    public JButton getBtnConsForn() {
        return btnConsForn;
    }

    public void setBtnConsForn(JButton btnConsForn) {
        this.btnConsForn = btnConsForn;
    }

    public JButton getBtnConsPeca() {
        return btnConsPeca;
    }

    public void setBtnConsPeca(JButton btnConsPeca) {
        this.btnConsPeca = btnConsPeca;
    }

    public JButton getBtnCadAdm() {
        return btnCadAdm;
    }

    public void setBtnCadAdm(JButton btnCadAdm) {
        this.btnCadAdm = btnCadAdm;
    }

    public void setBtnCadCarro(JButton btnCadCarro) {
        this.btnCadCarro = btnCadCarro;
    }

    public void setBtnCadCli(JButton btnCadCli) {
        this.btnCadCli = btnCadCli;
    }

    public void setBtnCadForn(JButton btnCadForn) {
        this.btnCadForn = btnCadForn;
    }

    public void setBtnCadPeca(JButton btnCadPeca) {
        this.btnCadPeca = btnCadPeca;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}