/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.consulta.ConsUsuario;
import visao.consulta.ConsPeca;
import visao.consulta.ConsPadrao;
import visao.consulta.ConsOrdemServico;
import visao.consulta.ConsFornecedor;
import visao.consulta.ConsCliente;
import visao.consulta.ConsCarro;
import visao.consulta.ConsAdministrador;
import visao.cadastro.CadtUsuario;
import visao.cadastro.CadPadrao;
import visao.cadastro.CadOrdemServico;
import visao.cadastro.CadCarros;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import visao.cadastro.CadAdministrador;
import visao.cadastro.CadClientes;
import visao.cadastro.CadFornecedor;
import visao.cadastro.CadPeca;

/**
 *
 * @author bruno
 */
public class Principal extends javax.swing.JFrame {

    //private int idUsuario;
    private Login log;
    private CadtUsuario caUs;
    private ConsUsuario conUs;
    private ConsOrdemServico conOS;
    private CadOrdemServico cadOS;
    private ConsAdministrador conAdm;
    private ConsCarro conCar;
    private ConsCliente conClie;
    private ConsFornecedor conForn;
    private ConsPeca conPeca;
    private CadAdministrador cadAdm;
    private CadCarros cadCar;
    private CadClientes cadCli;
    private CadFornecedor cadForn;
    private CadPeca cadPeca;
    private final List<CadPadrao> lstCad;
    private final List<ConsPadrao> lstCons;
    protected Object obj;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.jButton3.setVisible(false);
        this.jButton6.setVisible(false);
        this.jBtnConsAdm.setVisible(false);
        this.jBtnConsCarros.setVisible(false);
        this.jBtnConsCli.setVisible(false);
        this.jBtnConsForn.setVisible(false);
        this.jBtnConsPeca.setVisible(false);
        this.jBtnCadAdmin.setVisible(false);
        this.jBtnCadCarros.setVisible(false);
        this.jBtnCadClientes.setVisible(false);
        this.jBtnCadFornec.setVisible(false);
        this.jBtnCadPecas.setVisible(false);
        this.jLabel2.setVisible(true);
        this.lstCad  = new ArrayList<>();
        this.lstCons = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jBtnConsAdm = new javax.swing.JButton();
        jBtnConsCarros = new javax.swing.JButton();
        jBtnConsCli = new javax.swing.JButton();
        jBtnConsForn = new javax.swing.JButton();
        jBtnConsPeca = new javax.swing.JButton();
        jBtnCadAdmin = new javax.swing.JButton();
        jBtnCadCarros = new javax.swing.JButton();
        jBtnCadClientes = new javax.swing.JButton();
        jBtnCadFornec = new javax.swing.JButton();
        jBtnCadPecas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OSTPA");

        jButton1.setLabel("Cadastrar usuário");
        jButton1.setName("btnCadastrar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Consultar OS");
        jButton2.setName("btnConsultar"); // NOI18N
        jButton2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton2ComponentShown(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cons. usuários");
        jButton3.setName("btnConsultar"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Login");
        jButton4.setName(""); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Sair");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cadastrar OS");
        jButton6.setActionCommand("");
        jButton6.setName("btnConsultar"); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jBtnConsAdm.setText("Consultar adm.");
        jBtnConsAdm.setName("btnConsultar"); // NOI18N
        jBtnConsAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConsAdmMouseClicked(evt);
            }
        });
        jBtnConsAdm.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBtnConsAdmComponentShown(evt);
            }
        });
        jBtnConsAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsAdmActionPerformed(evt);
            }
        });

        jBtnConsCarros.setText("Cons. carros");
        jBtnConsCarros.setName("btnConsultar"); // NOI18N
        jBtnConsCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConsCarrosMouseClicked(evt);
            }
        });
        jBtnConsCarros.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBtnConsCarrosComponentShown(evt);
            }
        });
        jBtnConsCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsCarrosActionPerformed(evt);
            }
        });

        jBtnConsCli.setText("Consultar clientes");
        jBtnConsCli.setName("btnConsultar"); // NOI18N
        jBtnConsCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConsCliMouseClicked(evt);
            }
        });
        jBtnConsCli.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBtnConsCliComponentShown(evt);
            }
        });
        jBtnConsCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsCliActionPerformed(evt);
            }
        });

        jBtnConsForn.setText("Cons. fornecedor");
        jBtnConsForn.setName("btnConsultar"); // NOI18N
        jBtnConsForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConsFornMouseClicked(evt);
            }
        });
        jBtnConsForn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBtnConsFornComponentShown(evt);
            }
        });
        jBtnConsForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsFornActionPerformed(evt);
            }
        });

        jBtnConsPeca.setText("Consultar peças");
        jBtnConsPeca.setName("btnConsultar"); // NOI18N
        jBtnConsPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConsPecaMouseClicked(evt);
            }
        });
        jBtnConsPeca.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jBtnConsPecaComponentShown(evt);
            }
        });
        jBtnConsPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsPecaActionPerformed(evt);
            }
        });

        jBtnCadAdmin.setText("Cadastrar admin.");
        jBtnCadAdmin.setName("btnCadastrar"); // NOI18N
        jBtnCadAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCadAdminMouseClicked(evt);
            }
        });
        jBtnCadAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadAdminActionPerformed(evt);
            }
        });

        jBtnCadCarros.setText("Cadastrar carros");
        jBtnCadCarros.setName("btnCadastrar"); // NOI18N
        jBtnCadCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCadCarrosMouseClicked(evt);
            }
        });
        jBtnCadCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadCarrosActionPerformed(evt);
            }
        });

        jBtnCadClientes.setText(" Cadastrar clientes");
        jBtnCadClientes.setName("btnCadastrar"); // NOI18N
        jBtnCadClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCadClientesMouseClicked(evt);
            }
        });
        jBtnCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadClientesActionPerformed(evt);
            }
        });

        jBtnCadFornec.setText(" Cad. fornecedor");
        jBtnCadFornec.setName("btnCadastrar"); // NOI18N
        jBtnCadFornec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCadFornecMouseClicked(evt);
            }
        });
        jBtnCadFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadFornecActionPerformed(evt);
            }
        });

        jBtnCadPecas.setText("Cadastrar peças");
        jBtnCadPecas.setName("btnCadastrar"); // NOI18N
        jBtnCadPecas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCadPecasMouseClicked(evt);
            }
        });
        jBtnCadPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadPecasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setText("Sistema para controle de OS");

        jLabel2.setToolTipText("");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setOpaque(true);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bruno Reinicke\\Pictures\\Oficina Reinicke 700.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnCadAdmin)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConsAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnConsCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnConsCli)
                                .addGap(12, 12, 12)
                                .addComponent(jBtnConsForn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnCadCarros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCadClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnCadFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCadPecas)
                            .addComponent(jBtnConsPeca)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1106, 1106, 1106)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel4))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1381, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jBtnCadAdmin)
                    .addComponent(jBtnCadCarros)
                    .addComponent(jBtnCadClientes)
                    .addComponent(jBtnCadFornec)
                    .addComponent(jBtnCadPecas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jBtnConsAdm)
                    .addComponent(jButton2)
                    .addComponent(jBtnConsCarros)
                    .addComponent(jBtnConsCli)
                    .addComponent(jBtnConsForn)
                    .addComponent(jBtnConsPeca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.caUs = new CadtUsuario();
        this.caUs.setVisible(true);
        this.lstCad.add(this.caUs);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.conOS = new ConsOrdemServico();
        this.conOS.setIdUsuario(this.log.getIdUsuario());
        this.conOS.listar("");
        this.lstCons.add(this.conOS);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.conUs = new ConsUsuario();
        this.conUs.listar("");
        this.conUs.setVisible(true);
        this.lstCons.add(this.conUs);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.log = new Login();
        this.log.setBtnCadUsu(this.jButton1);
        this.log.setBtnConsUsu(this.jButton3);
        this.log.setBtnConsOS(this.jButton2);
        this.log.setBtnCadOS(this.jButton6);
        this.log.setBtnLogin(this.jButton4);
        this.log.setBtnConsAdm(this.jBtnConsAdm);
        this.log.setBtnConsCar(this.jBtnConsCarros);
        this.log.setBtnConsClie(this.jBtnConsCli);
        this.log.setBtnConsForn(this.jBtnConsForn);
        this.log.setBtnConsPeca(this.jBtnConsPeca);
        this.log.setBtnCadAdm(this.jBtnCadAdmin);
        this.log.setBtnCadCarro(this.jBtnCadCarros);
        this.log.setBtnCadCli(this.jBtnCadClientes);
        this.log.setBtnCadForn(this.jBtnCadFornec);
        this.log.setBtnCadPeca(this.jBtnCadPecas);
        this.log.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void fecharTelaCons() {
        for (int i = 0; i < this.lstCons.size(); i++)
            this.lstCons.get(i).dispose();
    }
    
    private void fecharTelaCad() {
        for (int i = 0; i < this.lstCad.size(); i++) {
            for (int y = 0; y < this.lstCad.get(i).getLstCons().size(); y++)
                this.lstCad.get(i).getLstCons().get(y).dispose();
            this.lstCad.get(i).dispose();
        }
    }
    
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.jButton3.setVisible(false);
        this.jButton6.setVisible(false);
        this.jBtnConsAdm.setVisible(false);
        this.jBtnConsCarros.setVisible(false);
        this.jBtnConsCli.setVisible(false);
        this.jBtnConsForn.setVisible(false);
        this.jBtnConsPeca.setVisible(false);
        this.jBtnCadAdmin.setVisible(false);
        this.jBtnCadCarros.setVisible(false);
        this.jBtnCadClientes.setVisible(false);
        this.jBtnCadFornec.setVisible(false);
        this.jBtnCadPecas.setVisible(false);
        this.jButton4.setEnabled(true);
        
        this.fecharTelaCad();
        this.fecharTelaCons();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton2ComponentShown
        this.log.dispose();
    }//GEN-LAST:event_jButton2ComponentShown

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        this.cadOS = new CadOrdemServico();
        this.cadOS.setVisible(true);
        this.cadOS.setIdUsuario(this.log.getIdUsuario());
        this.lstCad.add(this.cadOS);
    }//GEN-LAST:event_jButton6MouseClicked
    
    private void jBtnConsAdmComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnConsAdmComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsAdmComponentShown

    private void jBtnConsAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsAdmActionPerformed

    private void jBtnConsAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsAdmMouseClicked
        this.conAdm = new ConsAdministrador();
        this.conAdm.listar("");
        this.conAdm.setVisible(true);
        this.lstCons.add(this.conAdm);
    }//GEN-LAST:event_jBtnConsAdmMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBtnConsCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsCarrosMouseClicked
        this.conCar = new ConsCarro();
        this.conCar.listar("");
        this.conCar.setVisible(true);
        this.lstCons.add(this.conCar);
    }//GEN-LAST:event_jBtnConsCarrosMouseClicked

    private void jBtnConsCarrosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnConsCarrosComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsCarrosComponentShown

    private void jBtnConsCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsCarrosActionPerformed

    private void jBtnConsCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsCliMouseClicked
        this.conClie = new ConsCliente();
        this.conClie.listar("");
        this.conClie.setVisible(true);
        this.lstCons.add(this.conClie);
    }//GEN-LAST:event_jBtnConsCliMouseClicked

    private void jBtnConsCliComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnConsCliComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsCliComponentShown

    private void jBtnConsCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsCliActionPerformed

    private void jBtnConsFornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsFornMouseClicked
        this.conForn = new ConsFornecedor();
        this.conForn.listar("");
        this.conForn.setVisible(true);
        this.lstCons.add(this.conForn);
    }//GEN-LAST:event_jBtnConsFornMouseClicked

    private void jBtnConsFornComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnConsFornComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsFornComponentShown

    private void jBtnConsFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsFornActionPerformed
       
    }//GEN-LAST:event_jBtnConsFornActionPerformed

    private void jBtnConsPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsPecaMouseClicked
        this.conPeca = new ConsPeca();
        this.conPeca.listar("");
        this.conPeca.setVisible(true);
        this.lstCons.add(this.conPeca);
    }//GEN-LAST:event_jBtnConsPecaMouseClicked

    private void jBtnConsPecaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jBtnConsPecaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsPecaComponentShown

    private void jBtnConsPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConsPecaActionPerformed

    private void jBtnCadAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCadAdminActionPerformed

    private void jBtnCadAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadAdminMouseClicked
        this.cadAdm = new CadAdministrador();
        this.cadAdm.setVisible(true);
        this.lstCad.add(this.cadAdm);
    }//GEN-LAST:event_jBtnCadAdminMouseClicked

    private void jBtnCadCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadCarrosMouseClicked
        this.cadCar = new CadCarros();
        this.cadCar.setVisible(true);
        this.lstCad.add(this.cadCar);
    }//GEN-LAST:event_jBtnCadCarrosMouseClicked

    private void jBtnCadCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCadCarrosActionPerformed

    private void jBtnCadClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadClientesMouseClicked
        this.cadCli = new CadClientes();
        this.cadCli.setVisible(true);
        this.lstCad.add(this.cadCli);
    }//GEN-LAST:event_jBtnCadClientesMouseClicked

    private void jBtnCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCadClientesActionPerformed

    private void jBtnCadFornecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadFornecMouseClicked
        this.cadForn = new CadFornecedor();
        this.cadForn.setVisible(true);
        this.lstCad.add(this.cadForn);
    }//GEN-LAST:event_jBtnCadFornecMouseClicked

    private void jBtnCadFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadFornecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCadFornecActionPerformed

    private void jBtnCadPecasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCadPecasMouseClicked
        this.cadPeca = new CadPeca();
        this.cadPeca.setVisible(true);
        this.lstCad.add(this.cadPeca);
    }//GEN-LAST:event_jBtnCadPecasMouseClicked

    private void jBtnCadPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCadPecasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadAdmin;
    private javax.swing.JButton jBtnCadCarros;
    private javax.swing.JButton jBtnCadClientes;
    private javax.swing.JButton jBtnCadFornec;
    private javax.swing.JButton jBtnCadPecas;
    private javax.swing.JButton jBtnConsAdm;
    private javax.swing.JButton jBtnConsCarros;
    private javax.swing.JButton jBtnConsCli;
    private javax.swing.JButton jBtnConsForn;
    private javax.swing.JButton jBtnConsPeca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton4() {
        return this.jButton4;
    }
}